### PR TITLE
Added code to clear up the IKE between information sends in order to not have trailing characters from whatever was displayed on IKE cluster

### PR DESCRIPTION
**Pull request by zarboz**
In this request I have added code to inject a clear data display packet into the IKE cluster before injecting a text packet to display 

this ensures no trailing data or information from whatever we were looking at prior on the IKE cluster to starting pyBus 

I also added an injection packet on pollresponse

this packet renames CD->mp3 on our head unit 

just seemed fitting

### CODE REVIEW

**Comment by zarboz** [comment]
That’s probably a much cleaner way to implement the change I can do that this evening unless you beat me to it

**Comment by ezeakeal** [comment]
Actually, I will merge this request now and then start a new branch for a refactor.

Trying to read over code this old is a pain, and the design is a little weird to me now.
That being said, I'm not sure how long it will take me to write it.

**Comment by zarboz** [comment]
I am going to try to re write tonight 

I taught myself python for this but I’m well versed in C so it makes some sense

**Comment by zarboz** [comment]
@ezeakeal  I added a commit on my fork to make this a more centralized command once I run a test ill re open a pull for it

**Pull request merged**
